In [1]:
import numpy as np 

### Scalars

In [2]:
x = np.array(12)

In [3]:
x

array(12)

In [4]:
x.shape

()

In [5]:
x.ndim

0

### Vectors - 1D Tensor

In [6]:
x = np.array([1,2,3,4])

In [7]:
x

array([1, 2, 3, 4])

In [8]:
x.shape

(4,)

In [9]:
x.ndim

1

### Matrices - 2D Tensors

In [11]:
x = np.array([[1,2,3],
            [4,5,6]])

In [12]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
x.shape

(2, 3)

In [14]:
x.ndim

2

### 3D Tensors or High Dimensional Tensors

In [15]:
x = np.array([[[1,2,3],[4,5,6]],
              [[7,8,9],[1,2,3]]])

In [16]:
x

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

In [17]:
x.shape

(2, 2, 3)

In [18]:
x.ndim

3

### Key Attributes

- Number of axes = Esentially the number of dimensions
- Shape - Describes how many dimesnions does the data have along that axis
- Data Type - (dtype) - Mostly float32, uint8, float62, and so on.