The working of the neural network can be decomposed into a set of tensor operations, i.e. a set of tensor operations being performed on a Tensors. 

Consider for instance - 

> keras.layers.dense(512, activation = 'relu')

The layer can be interpreted as a function, which takes a 2D tensor as a input and outputs a 2D tensor as an output. 

Basically the above line does the following function. 

> output = relu(dot(W,input) + b )

Here the operations relu and addition operations are element wise operations

*This is the numpy implementation of element wise operations*

In [1]:
import numpy as np 

In [2]:
x = np.array([1,2,3])

In [3]:
y = np.array([4,5,6])

In [9]:
## Element Wise Addition
z = x + y 

In [10]:
z

array([5, 7, 9])

In [11]:
## Element WIse RELU
z = np.maximum(z, 0.)

In [12]:
z

array([5., 7., 9.])

### Broadcasting 

What happens when we try to add two tensors of different shapes?

*If there is no ambiguity the smaller tensor will get broadcasted on the larger one*
- Axes(called broadcast axes) are added to the smaller tensor to match the ndim of the larger tensor. 
- The smaller tensor is repeated alongside these new axes to match the full shape of the larger tensor.

In [13]:
x = np.random.random((64,3,32,10))

In [14]:
y = np.random.random((32,10))

In [15]:
z = np.maximum(x,y)

In [16]:
z.shape

(64, 3, 32, 10)

### Tensor Dot Product

**Not to be confused with element wise product**

It combines the entries after element wise product. Element Wise product is done with * operator. 
In tensorflow the dot uses a different syntax, but in Keras and Numpy the operation is as follows. 

In [22]:
x = np.random.random((12,12))

In [23]:
y = np.random.random((12))

In [29]:
## Dot product of Matrix and vector is a vector
z = np.dot(x,y)

In [30]:
z.shape

(12,)

In [31]:
## Element wise product by Broadcast
z = x*y

In [32]:
z.shape

(12, 12)

### Tensor Reshaping 

In [33]:
x = np.array([[1,2],
             [3,4],
             [5,6]])

In [34]:
x.shape

(3, 2)

In [35]:
x = x.reshape((6,1))

In [36]:
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [37]:
x = x.reshape((2,3))

In [38]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
## Transpose can also be taken. This is esentially swapping rows and columns. So, here the x[i,:] becomes x[:,i]

x = np.transpose(x)

In [40]:
x.shape

(3, 2)

In [41]:
x

array([[1, 4],
       [2, 5],
       [3, 6]])